import type { Metadata } from "next";
import {
    Geist,
    Geist_Mono,
    IBM_Plex_Mono,
    IBM_Plex_Sans,
} from "next/font/google";
import "./globals.css";
import "./globals.scss";
import Providers from "./providers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// Configure Sans Serif (Main UI Font)
const plexSans = IBM_Plex_Sans({
    subsets: ["latin"],
    weight: ["300", "400", "600"],
    display: "swap",
    variable: "--cds-font-family-sans", // Custom variable for Carbon
});

// Configure Mono (Code/Data Font)
const plexMono = IBM_Plex_Mono({
    subsets: ["latin"],
    weight: ["300", "400"],
    display: "swap",
    variable: "--cds-font-family-mono",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${plexSans.variable} ${plexMono.variable} antialiased`}
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
