import type { Metadata } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import "./globals.scss";
import Providers from "./providers"; // Ensure the filename case matches (Providers vs providers)

// Configure IBM Plex Sans (Carbon's default UI font)
const plexSans = IBM_Plex_Sans({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "600"],
    display: "swap",
    variable: "--cds-font-family-sans",
});

// Configure IBM Plex Mono
const plexMono = IBM_Plex_Mono({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700"],
    display: "swap",
    variable: "--cds-font-family-mono",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${plexSans.variable} ${plexMono.variable}`}
            >
            <div className="font-sans!">
                <Providers>{children}</Providers>
            </div>
            </body>
        </html>
    );
}
