import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./globals.scss";
import Providers from "./providers"; // Ensure the filename case matches (Providers vs providers)

// Configure IBM Plex Sans (Carbon's default UI font)
const plexSans = localFont({
  src: [
    {
      path: "../node_modules/@ibm/plex-sans/fonts/complete/woff2/IBMPlexSans-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../node_modules/@ibm/plex-sans/fonts/complete/woff2/IBMPlexSans-ExtraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../node_modules/@ibm/plex-sans/fonts/complete/woff2/IBMPlexSans-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../node_modules/@ibm/plex-sans/fonts/complete/woff2/IBMPlexSans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../node_modules/@ibm/plex-sans/fonts/complete/woff2/IBMPlexSans-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--cds-font-family-sans",
});

// Configure IBM Plex Mono
const plexMono = localFont({
  src: [
    {
      path: "../node_modules/@ibm/plex-mono/fonts/complete/woff2/IBMPlexMono-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../node_modules/@ibm/plex-mono/fonts/complete/woff2/IBMPlexMono-ExtraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../node_modules/@ibm/plex-mono/fonts/complete/woff2/IBMPlexMono-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../node_modules/@ibm/plex-mono/fonts/complete/woff2/IBMPlexMono-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../node_modules/@ibm/plex-mono/fonts/complete/woff2/IBMPlexMono-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../node_modules/@ibm/plex-mono/fonts/complete/woff2/IBMPlexMono-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../node_modules/@ibm/plex-mono/fonts/complete/woff2/IBMPlexMono-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--cds-font-family-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${plexSans.variable} ${plexMono.variable}`}>
        <div className="font-sans!">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
